- name: Create .env
  template:
    src: templates/.env.j2
    dest: "/{{ app_directory }}/docker/.env"
    owner: "{{ maintainer_user }}"
    group: "{{ maintainer_user }}"
    mode: '755'

- name: Create docker-compose.yml
  template:
    src: templates/docker-compose.yml.j2
    dest: "/{{ app_directory }}/docker/docker-compose.yml"
    owner: "{{ maintainer_user }}"
    group: "{{ maintainer_user }}"
    mode: '755'

- name: Docker compose down
  docker_compose:
    project_src: "{{ app_directory }}/docker"
    state: absent

- name: Docker compose up
  docker_compose:
    project_src: "{{ app_directory }}/docker"
    state: present
