- name: Deploy
  hosts: prod_servers
  become: true
  become_user: "{{ maintainer_user }}"
  vars_files:
    - vars.yml
  roles:
    - files
    - docker
    - build_back
    - build_front
    - apache
